name: New Feature
description: 새로운 기능을 구현합니다.
title: "[Feat]: "
labels: ["🌈 feature"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        새로운 기능 구현에 대한 이슈입니다.
  - type: textarea
    id: background
    attributes:
      label: 배경
      description: 왜 이런 기능을 넣으려는지 설명합니다.
      placeholder: 설명
    validations:
      required: true
  - type: textarea
    id: new-feature
    attributes:
      label: 내용
      description: 구현기능을 나열하고, 어떻게 구현할지 등을 자세하게 설명합니다.
      placeholder: 설명
    validations:
      required: true
  - type: textarea
    id: reference
    attributes:
      label: 참고
      description: 참고할 문서, 링크가 있으면 작성해주세요.
    validations:
      required: false
