package tetrisgame.enumerations;

public enum eMsg {
    NONE,
    COLL_WITH_FLOOR,
    WEIGHT_ITEM_COLL_WITH_FLOOR,
    LINEERASER_ITEM_COLL_WITH_FLOOR,
    SLOWING_ITEM_ERASED,
    FOCUS_ANIM_OVER,
    GAME_OVER,

    ERASE_10xN_LINES,

    LINE_REMOVE_0,
    LINE_REMOVE_1,
    LINE_REMOVE_2,
    LINE_REMOVE_3,
    LINE_REMOVE_4,
    LINE_REMOVE_5,
    LINE_REMOVE_6,
    LINE_REMOVE_7,
    LINE_REMOVE_8,
    LINE_REMOVE_9,
    LINE_REMOVE_10,
    LINE_REMOVE_11,
    LINE_REMOVE_12,
    LINE_REMOVE_13,
    LINE_REMOVE_14,
    LINE_REMOVE_15,
    LINE_REMOVE_16,
    LINE_REMOVE_17,
    LINE_REMOVE_18,
    LINE_REMOVE_19,
}
